# Generated by Django 5.2 on 2026-02-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CERAMICA', 'Cerámica'), ('TEJIDOS', 'Tejidos'), ('MADERA', 'Madera')], default='CERAMICA', max_length=20),
        ),
    ]
