# Generated by Django 5.2 on 2026-02-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_producto_imagen_url_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Está a la venta?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad en Inventario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CERAMICA', 'Cerámica'), ('TEJIDOS', 'Tejidos'), ('MADERA', 'Madera')], default='CERAMICA', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='Precio de Venta'),
        ),
    ]
